-- ==========================================================
-- DADOS DE TESTE
--
-- Não tem mais o que semear aqui. No desenho antigo (escritório
-- com equipe compartilhada) fazia sentido pré-cadastrar uns
-- advogados de exemplo, porque o cadastro era um convite feito
-- por um admin. Agora o Juris é por advogado, sem admin, e o
-- cadastro é público: o trigger handle_new_user cria o perfil na
-- hora em que a conta nasce.
--
-- Para ter um usuário de teste no ambiente local, cadastre-se
-- pela própria tela de login do app (npm run dev, com
-- VITE_SUPABASE_URL apontando para http://127.0.0.1:54321) — o
-- cadastro público já funciona local e em produção.
-- ==========================================================
